# Update Time: 2023-05-20 21:57
version: "3.4"

services:
  # NocoBase
  nocobase:
    image: nocobase/nocobase:main
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      DB_LOGGING: ${DB_LOGGING}       
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LOCAL_STORAGE_BASE_URL: ${LOCAL_STORAGE_BASE_URL}
      TZ: ${TZ}
    volumes:
      - nfs_nocobase:/app/nocobase/storage
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nocobase.rule=Host(`nocobase.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.nocobase.entrypoints=websecure"
        - "traefik.http.routers.nocobase.service=nocobase"
        - "traefik.http.routers.nocobase.middlewares=noauth-chain@file"
        - "traefik.http.services.nocobase.loadbalancer.server.port=80"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.application == true

  # Transmission
  transmission:
    image: helloz/transmission:latest
    networks: [network_cluster]
    restart: on-failure  
    environment:
      # 直接使用Portainer容器内的环境变量
      USERNAME: ${PT_USERNAME}       
      PASSWORD: ${PT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - /dev/sdb1:/root/Downloads
      - nfs_transmission:/root/.config/transmission-daemon
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transmission.rule=Host(`pt.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.service=transmission"
        - "traefik.http.routers.transmission.middlewares=noauth-chain@file"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"
        - "traefik.tcp.routers.torrent.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.torrent.entrypoints=torrent"
        - "traefik.tcp.routers.torrent.service=torrent"
        - "traefik.tcp.services.torrent.loadbalancer.server.port=51413"        
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.download == true

networks:
  network_cluster:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

volumes:
  # NFS
  nfs_nocobase:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/business/nocobase/storage
  nfs_transmission:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/download/transmission/config