# Update Time: 2023-11-19 23:50
version: "3.4"

services:
  # XiaoaiGPT
  xiaogpt1:
    image: yihong0618/xiaogpt
    command: --config=/config/config.json
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      TZ: ${TZ}
    volumes:
      - nfs_xiaogpt_config1:/config
      - nfs_xiaogpt_src:/app/xiaogpt 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.ai == true
  xiaogpt2:
    image: yihong0618/xiaogpt
    command: --config=/config/config.json
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      TZ: ${TZ}
    volumes:
      - nfs_xiaogpt_config2:/config
      - nfs_xiaogpt_src:/app/xiaogpt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.ai == true
  xiaogpt3:
    image: yihong0618/xiaogpt
    command: --config=/config/config.json
    networks: [network_cluster]
    restart: on-failure
    environment:
      # 直接使用Portainer容器内的环境变量
      TZ: ${TZ}
    volumes:
      - nfs_xiaogpt_config3:/config
      - nfs_xiaogpt_src:/app/xiaogpt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.ai == true                    

networks:
  network_cluster:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

volumes:
  # NFS
  nfs_xiaogpt_src:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/ai/xiaogpt/src/xiaogpt        
  nfs_xiaogpt_config1:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/ai/xiaogpt/config1
  nfs_xiaogpt_config2:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/ai/xiaogpt/config2
  nfs_xiaogpt_config3:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/application/ai/xiaogpt/config3         